parameters:
- name: "serviceName"
  type: string
- name: "environment"
  type: string
- name: "imageTag"
  type: string
  default: 'latest'

jobs:
  - deployment: UpdateGitOps
    displayName: "Update GitOps Repo (image tag)"
    environment: ${{parameters.environment}}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              persistCredentials: true
              clean: true

            - task: Bash@3
              displayName: Update GitOps Repo
              inputs:
                targetType: inline
                script: |
                  git config --global user.email "santosh.mohapatra25@gmail.com"
                  git config --global user.name "Santosh Mohapatra"
                  git clone https://github.com/santosh-gh/k8s-21-deployment.git
                  cd k8s-21-deployment

                  if [ "${{parameters.serviceName}}" != "config" ]; then

                    if [ "${{parameters.serviceName}}" != "rabbitmq" ]; then
                      
                      echo "Updating deployment files with image tags..."
                      sed -i "s|acronlinestoredevuksouth001.azurecr.io/${{parameters.serviceName}}|acronlinestoredevuksouth001.azurecr.io/${{parameters.serviceName}}:${{parameters.imageTag}}|g"  kustomize-manifests/${{parameters.serviceName}}/base/deployment.yaml                  
                      cat kustomize-manifests/${{parameters.serviceName}}/base/deployment.yaml
                    else                     
                      
                      echo "Updating deployment files with image tags..."
                      sed -i "s|acronlinestoredevuksouth001.azurecr.io/${{parameters.serviceName}}|acronlinestoredevuksouth001.azurecr.io/${{parameters.serviceName}}:${{parameters.imageTag}}|g"  kustomize-manifests/${{parameters.serviceName}}/base/statefulset.yaml
                      cat kustomize-manifests/${{parameters.serviceName}}/base/statefulset.yaml

                    fi
                  else
                    echo "Skipping image tag update for service 'config'"
                  fi

                  git add .
                  git commit -m "Updated ${{parameters.serviceName}} with Tag: ${{parameters.imageTag}}"
                  git push https://$(GITHUB-PAT)@github.com/santosh-gh/k8s-21-deployment.git HEAD:main